spring:
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
